### ISSUE TITLE
Unexpected input(s) 'extra-arduino-cli-args'

### ISSUE THREAD

**Issue by DustinWatts** [ArminJo/arduino-test-compile#27]
When try to set `"--warnings default"` as per the documentation: https://github.com/ArminJo/arduino-test-compile#extra-arduino-cli-args

I get the follwing error when I try to run the workflow:

```
Unexpected input(s) 'extra-arduino-cli-args', valid inputs are ['cli-version', 'sketch-names', 
'sketch-names-find-start', 'arduino-board-fqbn', 'arduino-platform', 'platform-default-url', 
'platform-url', 'required-libraries', 'sketches-exclude', 'build-properties',
'set-build-path', 'debug-compile', 'debug-install']
```

This fails the workflow run. Becasue some of the liraries used give warnigs.

This is the part of my .yaml that includes the `extra-arduino-cli-args`:

```
- name: Test compile for Arduino
   uses: ArminJo/arduino-test-compile@v3.0.0
   with: 
        arduino-board-fqbn: esp32:esp32:esp32:PartitionScheme=no_ota
        extra-arduino-cli-args: "--warnings default"
        platform-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
        required-libraries: ArduinoJson
```
