### ISSUE TITLE
[feature request] : accept "latest" as platform-version in ARDUINO_PLATFORM

### ISSUE THREAD

**Issue by tobozo** [ArminJo/arduino-test-compile#32]
Hi, 

thanks for this great project :+1: 

Some context: one of my workflows creates a multidimensional matrix from different combinations of platform/architectures/board/version.

I'm running arduino-test-compile a a step in that matrix:

```yml
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Compile example
        uses: ArminJo/arduino-test-compile@v3
        with:
          arduino-board-fqbn: ${{matrix.platform}}:${{matrix.archi}}:${{matrix.board}}
          arduino-platform: ${{matrix.platform}}:${{matrix.archi}}@${{matrix.platform-version}}
          platform-url: ${{ matrix.platform-url }}
          required-libraries: ${{ matrix.required-libraries }}
          extra-arduino-cli-args: ${{ matrix.cli-args }}
```

The `${{matrix.***}}` variables are dynamic but the separators `:` and `@` aren't.
So if one of them is missing, the FQBN becomes invalid.

```yml
          arduino-platform: ${{matrix.platform}}:${{matrix.archi}}@${{matrix.platform-version}}
```

So far so good, everything works fine as long as I'm implicitely listing all package **versions** I want to be tested.

However this requires maintenance every time a new package version appears (e.g. esp32 recently released `2.0.5` package).

[![image](https://user-images.githubusercontent.com/1893754/197394747-2cb5e0eb-bbbd-4b63-9fd7-c43fadf13d46.png)](https://github.com/tobozo/YAMLDuino/blob/1.2.9/.github/workflows/ArduinoBuild.yml)

Here's what I tried to achieve when I was still full of illusions, believing the Arduino CI woud somehow read my mind :-)

### set `${{matrix.platform-version}}` to `latest`

![image](https://user-images.githubusercontent.com/1893754/197395198-a87e742b-350a-4764-8af9-dda3e33aa536.png)

![image](https://user-images.githubusercontent.com/1893754/197395218-1579b106-5588-4090-b461-34e129e3473b.png)

Of course it fails! Why would `latest` be semver compliant? stupid me :facepalm: 

So here's my feature request: detecting a trailing `@latest` in the semver part of  `$ARDUINO_PLATFORM` and removing that trail from the FQBN so that Arduino CI just selects the latest version from the json package (which is the default behaviour) instead of erroring.

**Comment by tobozo** [comment]
Here's the detached approach I'm using if it can be of any help, it blindly removes all instances of `@latest` from the concatenated `arduino-platform` string, I'm not sure how it behaves with arrays though.

```yml
- name: FBQN Check
  run: |
    export ARDUINO_PLATFORM="${${{matrix.platform}}:${{matrix.archi}}@${{matrix.platform-version}}/@latest/""}"
    echo "ARDUINO_PLATFORM=$ARDUINO_PLATFORM" >> $GITHUB_ENV

- name: Compile example
  uses: ArminJo/arduino-test-compile@v3
  with:
    arduino-board-fqbn: ${{matrix.platform}}:${{matrix.archi}}:${{matrix.board}}
    arduino-platform: ${{env.ARDUINO_PLATFORM}}
    platform-url: ${{ matrix.platform-url }}
    extra-arduino-cli-args: ${{ matrix.cli-args }}
    sketch-names: ${{ env.SKETCH_NAME }}
```
